/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mr A McBride (https://sketchfab.com/lobsterfuric)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metallica-master-of-puppets-album-f4664dd4581f4485a4b7c8de836293af
Title: Metallica Master of Puppets album
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    const { nodes, materials } = useGLTF('/album.gltf');
    console.log("Textures in AlbumModel: ", props.frontCover, props.backCover);
    return (
        <group {...props} dispose={null}>
            <group scale={1}>
                <group position={[0, 0, -1.5]} rotation={[1.5, 0, 0]}>
                    <group position={[0, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface3_clear_plastic_0.geometry}
                            material={materials['clear_plastic']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface3_front_cover_0.geometry}
                            material={materials['front_cover']}
                        >
                            <meshStandardMaterial map={props.frontCover} />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface3_black_plastic_0.geometry}
                            material={materials['black_plastic']}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface3_back_cover_0.geometry}
                            material={materials['back_cover']}
                        >
                            <meshStandardMaterial map={props.backCover} />
                        </mesh>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.polySurface3_lambert1_0.geometry}
                            material={materials['lambert1']}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface1_clear_plastic_0.geometry}
                        material={materials['clear_plastic']}
                        position={[0, -3.512, -1.638]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.polySurface2_clear_plastic_0.geometry}
                        material={materials['clear_plastic']}
                        position={[0, 2.54, 1.184]}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/album.gltf')